apiVersion: v1
kind: ConfigMap
metadata:
  name: zjgpu-cm
  namespace: kube-system
data:
  config.json: |
    {
      "resourceName": "github.com/zjgpu",
      "socketName": "zjgpu.sock",
      "numDevices": 100,
      "hostDevices": [{
        "hostPath": "/dev/zjGPU",
        "containerPath": "/dev/zjGPU",
        "permission": "r"
      }]
    }
