apiVersion: v1
kind: ConfigMap
metadata:
  name: zjgpu-cm
  namespace: kube-system
data:
  config.json: |
    {
      "resourceName": "zhejianglab.com/gpu",
      "socketName": "zjgpu.sock",
      "numDevices": 2048,
      "hostDevices": [{
        "hostPath": "/dev/random",
        "containerPath": "/dev/random",
        "permission": "r"
      }]
    }
