apiVersion: v1
kind: ConfigMap
metadata:
  name: zjgpu-cm
  namespace: kube-system
data:
  config.json: |
    {
      "resourceName": "nvidia.com/gpu",
      "socketName": "zjgpu.sock",
      "numDevices": 10000,
      "hostDevices": [{
        "hostPath": "/dev/random",
        "containerPath": "/dev/random",
        "permission": "rwm"
      }]
    }
