apiVersion: v1
kind: Pod
metadata:
  name: zjgpu-test
spec:
  restartPolicy: OnFailure
  containers:
  - image: alpine
    name: zjgpu-test-ctr
    resources:
      limits:
        github.com/zjgpu: 8
    command:
    - sh
    - -c
    - |
      od -vAn -N4 -tu4 < /dev/random
      sleep 1000000
